version: 0.2

env:
    parameter-store:
        VAR_APP_PORT: /khanhwebportal/back-end/APP_PORT
        VAR_APP_HOSTNAME: /khanhwebportal/back-end/APP_HOSTNAME
        VAR_DB_USER: /khanhwebportal/back-end/DB_USER
        VAR_DB_PASSWORD: /khanhwebportal/back-end/DB_PASSWORD
        VAR_DB_HOST: /khanhwebportal/back-end/DB_HOST
        VAR_SECRET_KEY_BASE: /khanhwebportal/back-end/SECRET_KEY_BASE 

phases:
  install:
    run-as: root
    commands:
      - echo Entered the install phase ...
  pre_build:
    run-as: root
    commands:
      - echo Entered the pre_build phase ...
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - REPOSITORY_URI_nginx=756081003265.dkr.ecr.us-east-1.amazonaws.com/khanh-poc-nginx
      - REPOSITORY_URI_app=756081003265.dkr.ecr.us-east-1.amazonaws.com/khanh-poc-app
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    run-as: root
    commands:
      - echo Build started on `date`
      - echo Entered the build phase ...
      - echo Building the Docker image...         
      - echo Start running docker-compose in detach mode 
      - APP_PORT=$VAR_APP_PORT \
      - APP_HOSTNAME=$VAR_APP_HOSTNAME \
      - DB_PASSWORD=$VAR_DB_PASSWORD \
      - DB_USER=$VAR_DB_USER \
      - DB_HOST=$VAR_DB_HOST \
      - SECRET_KEY_BASE=$VAR_SECRET_KEY_BASE \
      - IMAGE_APP=$REPOSITORY_URI_app \
      - APP_TAG=$IMAGE_TAG \
      - IMAGE_NGINX=$REPOSITORY_URI_nginx \
      - NGINX_TAG=$IMAGE_TAG \
      - docker-compose build 
      - echo Pushing the Docker image...
      #- docker tag $REPOSITORY_URI_app:latest $REPOSITORY_URI_app:$IMAGE_TAG  
      #- docker tag $REPOSITORY_URI_nginx:latest $REPOSITORY_URI_nginx:$IMAGE_TAG  
  post_build:
    run-as: root
    commands:
      - echo Entered the post_build phase ...
      - docker push $REPOSITORY_URI_nginx:$IMAGE_TAG
      - docker push $REPOSITORY_URI_app:$IMAGE_TAG
      - printf '[{"name":"khanh_app","imageUri":"%s"}, {"name":"khanh_nginx","imageUri":"%s"}]' $REPOSITORY_URI_app:$IMAGE_TAG, $REPOSITORY_URI_nginx:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json