version: '3'
services:
  nginx:
    build:
      context: ./nginx
    image: ${IMAGE_NGINX}:${NGINX_TAG}
    ports:
      - 80:80
    links:
      - app
  app:
    build:
      context: .
    image: ${IMAGE_APP}:${APP_TAG}
    args:
      - APP_PORT=${APP_PORT}
      - APP_HOSTNAME=${APP_HOSTNAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}


