version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.18
    container_name: reverse_proxy
    depends_on:
      - react
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  react: 
    image: react
    container_name: react
    build: 
      context: ./react
    depends_on:
      - app
    ports:
      - 8080:80
    restart: on-failure
    
  app:
    image: app #${IMAGE_APP}:${APP_TAG}
    container_name: app
    build:
      context: ./app
      args:
        - APP_PORT=4000 #${APP_PORT}
        - APP_HOSTNAME=localhost #${APP_HOSTNAME}
        - DB_USER=postgres #${DB_USER}
        - DB_PASSWORD=postgres #${DB_PASSWORD}
        - DB_HOST=postgresql.chjup0ji0a5y.us-east-1.rds.amazonaws.com #${DB_HOST}
        - SECRET_KEY_BASE=FgpNsLszr+jdqyiHytZQNZ+FXUCK1yIUJEPUOUtJXEZK91ju/jFaGjwYaQDSQCkM #${SECRET_KEY_BASE}
    ports: 
      - 4000:4000
    restart: on-failure


